name: clean_project
description: "A new Flutter project."

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: '>=3.3.0-151.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.2
  get_it: ^7.6.6
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  alchemist: ^0.7.0
  platform: ^3.1.3
  file: ^7.0.0

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.7
 
  flutter_lints: ^3.0.0
  
  test: ^1.24.9

flutter:

 
  uses-material-design: true

  
   
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          weight: 600
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
